name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Pytests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest

  ContributorsCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Generate contributors file
        run: poetry run python scripts/generate_contributors.py

      - name: Check contributors file is up to date
        run: git diff --exit-code CONTRIBUTORS.md


  PrecommitCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install pre-commit hooks
        run: poetry run pre-commit install --install-hooks

      - name: Run all pre-commit hooks
        run: poetry run pre-commit run --all-files

  CoverageCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
        
      - name: Run tests with coverage
        run: poetry run pytest --cov=whiteboxml --cov-report=term-missing --cov-fail-under=80
